src/EkleftVendingMachine/Controllers/HomeController.cs
using Ekleft.VendingMachine.UI.Model;
using Ekleft.VendingMachine.UI.Services;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EkleftVendingMachine.Controllers
{
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var bulder = DependencyResolver.Current.GetService<IModelBuilder<IndexModel, EmptyArguments>>();
            var model = await bulder.Build(EmptyArguments.DefaultInstance);
            return View(model);
        }
	}
}

src/EkleftVendingMachine/Controllers/MachineController.cs
using Ekleft.VendingMachine.Business;
using Ekleft.VendingMachine.Business.Commands;
using Ekleft.VendingMachine.UI.Services;
using EkleftVendingMachine.Requests;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EkleftVendingMachine.Controllers
{
    /*
     * Я бы здесь использовал jquery, но к сожалению не 
     * было времени возиться с клиентской частью поэтому с перезагрузкой
     */
    public class MachineController : Controller
    {
        /// <summary>Добавляет монетку в торговый автомат</summary>
        [HttpPost]
        public async Task<ActionResult> PutCoin(AddCoinRequest request)
        {
            var command = DependencyResolver.Current.GetService<ICommand<PutCoinArguments>>();

            if (!ModelState.IsValid)
            { 
                TempData[KeysConstants.ErrorMessageKey] = "Неверный запрос";
                return RedirectToAction("Index", "Home");
            }

            var result = await command.Execute(new PutCoinArguments { CoinValue = request.CoinValue });

            if(result.IsSuccess)
            {
                TempData[KeysConstants.SuccessMessageKey] = "Монета успешно добавлена в автомат";
            }
            else TempData[KeysConstants.ErrorMessageKey] = result.Error.ErrorMessage;
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<ActionResult> BuyProduct(int productId)
        {
            var command = DependencyResolver.Current.GetService<ICommand<BuyProductArguments>>();

            if (productId < 1)
            {
                TempData[KeysConstants.ErrorMessageKey] = "Неверный запрос";
                return RedirectToAction("Index", "Home");
            }

            var result = await command.Execute(new BuyProductArguments { ProductId = productId });

            if (result.IsSuccess)
            {
                TempData[KeysConstants.SuccessMessageKey] = "Спасибо!";
            }
            else TempData[KeysConstants.ErrorMessageKey] = result.Error.ErrorMessage;

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<ActionResult> PayBack()
        {
            var command = DependencyResolver.Current.GetService<ICommand<PayBackArguments>>();
            var result = await command.Execute(new PayBackArguments { });

            if(!result.IsSuccess)
            {
                TempData[KeysConstants.ErrorMessageKey] = result.Error.ErrorMessage;
                return RedirectToAction("Index", "Home");
            }

            TempData[KeysConstants.SuccessMessageKey] = "Сдача успешно возвращена";
            return RedirectToAction("Index", "Home");
        }
    }
}

src/EkleftVendingMachine/Views/Home/Index.cshtml
@model Ekleft.VendingMachine.UI.Model.IndexModel
@using Ekleft.VendingMachine.UI.Services


@{
    ViewBag.Title = "Тестовое задание Алексея Поликарпова";
    Layout = "~/Views/Shared/Layouts/_Layout.cshtml";
}

<h2>Тестовое задание Алексея Поликарпова</h2>
@if (TempData[KeysConstants.ErrorMessageKey] != null)
{
    <div class="alert alert-danger">@TempData[KeysConstants.ErrorMessageKey]</div>
}

@if (TempData[KeysConstants.SuccessMessageKey] != null)
{
    <div class="alert alert-success">@TempData[KeysConstants.SuccessMessageKey]</div>
}


<div class="row">
    <div class="col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading">Информация о пользователе</div>
            <div class="panel-body">
                <div>
                    <strong>UserId:</strong> @Model.User.Id
                </div>
                <div>
                    <strong>Монеты:</strong>
                </div>
                <div class="row">
                    @foreach (var coin in Model.User.Coins)
                    {
                        <form action="@Url.Action("PutCoin", "Machine",new {CoinValue = coin.CoinValue})" method="post" class="col-xs-6">
                            <div>
                                <button type="submit" class="btn btn-default" @(coin.Count < 1 ? "disabled" : "")>
                                    @coin.CoinValue руб. (@coin.Count шт.)
                                </button>
                                <button type="submit" @(coin.Count <1 ? "disabled" : "") class="btn btn-link">Внести</button>
                            </div>
                            <br />
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading">Информация о торговом автомате</div>
            <div class="panel-body">
                <div>
                    <strong>Внесенная сумма:</strong> @Model.VendingMachine.DepositedAmount руб.
                    <form action="@Url.Action("PayBack", "Machine")" method="post">
                        <button type="submit" class="btn btn-default" @(Model.VendingMachine.DepositedAmount < 1 ? "disabled" : "")>
                            Вернуть сдачу
                        </button>
                    </form>
                </div>
                <div>
                    <strong>Товары:</strong>
                </div>
                <div class="row">
                    @foreach (var product in Model.VendingMachine.Products)
                    {
                        <form action="@Url.Action("BuyProduct", "Machine", new { ProductId = product.Id})" method="post" class="col-xs-6">
                            <div class="panel panel-default">
                                <div class="panel-heading">@product.Name</div>
                                <div class="panel-body">
                                    <div>
                                        <strong>Стоимость</strong>:
                                        @product.Cost руб.
                                    </div>
                                    <div>
                                        <strong>Количество</strong>:
                                        @product.Count
                                    </div>
                                    <div>
                                        <button type="submit" class="btn btn-default" @(product.Count < 1 ? "disabled" : "")>
                                            Купить
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    }
                </div>
                <div>
                    <strong>Монеты:</strong>
                </div>
                <div class="row">
                    @foreach (var coin in Model.VendingMachine.Coins)
                    {
                        <div class="col-xs-6">
                            <div>
                                <button type="button" class="btn btn-default disabled">
                                    @coin.CoinValue руб. (@coin.Count шт.)
                                </button>
                            </div>
                            <br />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

src/EkleftVendingMachine/Views/Shared/Layouts/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>    
    @Styles.Render("~/bundles/styles/main")
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="container">
        @RenderBody()

        <footer>
            @Scripts.Render("~/bundles/scripts/main")
            @RenderSection("Scripts", required: false)
        </footer>
    </div>    
</body>
</html>